# -*- coding: utf-8 -*-
"""BoW_test.ipynb

Automatically generated by Colaboratory.


# Imports
"""

# import re
import numpy 
from sklearn.feature_extraction.text import CountVectorizer 
from sklearn.tree import DecisionTreeClassifier as dt
# import a library to split the original dataset into random test and train subsets
from sklearn.model_selection import train_test_split
# libraries to evaluate the model
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.svm import NuSVC
from sklearn.svm import LinearSVC
import nltk 
from nltk.corpus import stopwords 
nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

"""# Create data"""

# training
corpus_train = [
    """
    Pediatrics (also spelled paediatrics or pædiatrics) is the branch of medicine that involves the medical care of infants, children, and adolescents. The American Academy of Pediatrics recommends people be under pediatric care up to the age of 21,[1] thought usually only minors under 18 are required to be under pediatric care. A medical doctor who specializes in this area is known as a pediatrician, or paediatrician. The word pediatrics and its cognates mean "healer of children"; they derive from two Greek words: παῖς (pais "child") and ἰατρός (iatros "doctor, healer"). Pediatricians work both in hospitals, particularly those working in its subspecialties such as neonatology, and as outpatient primary care physicians. 

    Already Hippocrates, Aristotle, Celsus, Soranus, and Galen[2] understood the differences in growing and maturing organisms that necessitated different treatment: Ex toto non sic pueri ut viri curari debent ("In general, boys should not be treated in the same way as men").[3]
    
    Some of the oldest traces of pediatrics can be discovered in Ancient India where children's doctors were called kumara bhrtya.[2] Sushruta Samhita an ayurvedic text, composed during the sixth century BC contains the text about pediatrics.[4] Another ayurvedic text from this period is Kashyapa Samhita.[5][6]

    A second century AD manuscript by the Greek physician and gynecologist Soranus of Ephesus dealt with neonatal pediatrics.[7] Byzantine physicians Oribasius, Aëtius of Amida, Alexander Trallianus, and Paulus Aegineta contributed to the field.[2] The Byzantines also built brephotrophia (crêches).[2] Islamic writers served as a bridge for Greco-Roman and Byzantine medicine and added ideas of their own, especially Haly Abbas, Serapion, Avicenna, and Averroes. The Persian philosopher and physician al-Razi (865–925) published a monograph on pediatrics titled Diseases in Children as well as the first definite description of smallpox as a clinical entity.[8][9] Also among the first books about pediatrics was Libellus [Opusculum] de aegritudinibus et remediis infantium 1472 ("Little Book on Children Diseases and Treatment"), by the Italian pediatrician Paolo Bagellardo.[10] In sequence came Bartholomäus Metlinger's Ein Regiment der Jungerkinder 1473, Cornelius Roelans (1450–1525) no title Buchlein, or Latin compendium, 1483, and Heinrich von Louffenburg (1391–1460) Versehung des Leibs written in 1429 (published 1491), together form the Pediatric Incunabula, four great medical treatises on children's physiology and pathology.[2]

    The Swedish physician Nils Rosén von Rosenstein (1706–1773) is considered to be the founder of modern pediatrics as a medical specialty,[11][12] while his work The diseases of children, and their remedies (1764) is considered to be "the first modern textbook on the subject".[13] Pediatrics as a specialized field of medicine continued to develop in the mid-19th century; German physician Abraham Jacobi (1830–1919) is known as the father of American pediatrics because of his many contributions to the field.[14][15] He received his medical training in Germany and later practiced in New York City.

    The first generally accepted pediatric hospital is the Hôpital des Enfants Malades (French: Hospital for Sick Children), which opened in Paris in June 1802 on the site of a previous orphanage.[16] From its beginning, this famous hospital accepted patients up to the age of fifteen years,[17] and it continues to this day as the pediatric division of the Necker-Enfants Malades Hospital, created in 1920 by merging with the physically contiguous Necker Hospital, founded in 1778.

    In other European countries, the Charité (a hospital founded in 1710) in Berlin established a separate Pediatric Pavilion in 1830, followed by similar institutions at Saint Petersburg in 1834, and at Vienna and Breslau (now Wrocław), both in 1837. In 1852 Britain's first pediatric hospital, the Hospital for Sick Children, Great Ormond Street was founded by Charles West.[16] The first Children's hospital in Scotland opened in 1860 in Edinburgh.[18] In the US, the first similar institutions were the Children's Hospital of Philadelphia, which opened in 1855, and then Boston Children's Hospital (1869).[19] Subspecialties in pediatrics were created at the Harriet Lane Home at Johns Hopkins by Edwards A. Park.[20] 
    """,
    
    """
    This is the branch of podiatry that is involved in the complex management of the foot and ankle involving surgery under both local and general anaesthetic. Having undergone undergraduate training and then a comprehensive postgraduate course in both academic and hands on practical training a podiatric surgeon will then work with treating things like bunions, hammer toes, neuromas, infections, osteoarthritis, ankle problems etc. Access to the full variety of imaging techniques is a fundamental part of their assessment and diagnosis. This along with the support of the multi-disciplinary team demonstrates who a podiatric surgeon is part of the wider health economy.
    """,
    
    """
    Pediatrics is the branch of medicine dealing with the health and medical care of infants, children, and adolescents from birth up to the age of 18. The word “paediatrics” means “healer of children”; they are derived from two Greek words: (pais = child) and (iatros = doctor or healer). Paediatrics is a relatively new medical specialty, developing only in the mid-19th century. Abraham Jacobi (1830–1919) is known as the father of paediatrics.

    What does a pediatrician do?
    A paediatrician is a child's physician who provides not only medical care for children who are acutely or chronically ill but also preventive health services for healthy children. A paediatrician manages physical, mental, and emotional well-being of the children under their care at every stage of development, in both sickness and health.

    Aims of pediatrics
    The aims of the study of paediatrics is to reduce infant and child rate of deaths, control the spread of infectious disease, promote healthy lifestyles for a long disease-free life and help ease the problems of children and adolescents with chronic conditions.

    Paediatricians diagnose and treat several conditions among children including:-

    injuries
    infections
    genetic and congenital conditions
    cancers
    organ diseases and dysfunctions
    Paediatrics is concerned not only about immediate management of the ill child but also long term effects on quality of life, disability and survival. Paediatricians are involved with the prevention, early detection, and management of problems including:-
    """,
    
    """
    Podiatry (/poʊˈdaɪ.ətri/ or podiatric medicine (/poʊdiˈætrɪk, -ˈdaɪ.ətrɪk/) is a branch of medicine devoted to the study, diagnosis, and medical and surgical treatment of disorders of the foot, ankle, and lower extremity. The term podiatry came into use in the early 20th century in the United States and is now used worldwide, including in countries such as the United Kingdom, Australia, and Canada.[1]

    Podiatry is practiced as a specialty in many countries, while in many English-speaking countries, the older title of chiropodist may be used by some clinicians[2] (not to be confused with chiropractics, which is unrelated). In Australia, graduates of recognised academic programs can register through the Podiatry Board of Australia as a "podiatrist", and those with additional recognised training may also receive endorsement to prescribe or administer restricted medications and/or seek specialist registration as a "podiatric surgeon". In many non-English-speaking countries of Europe, the title used may be podologue (French)[3] or podólogo (Spanish and Italian).[4] The level and scope of the practice of podiatry vary among countries.

    According to the American Association of Colleges of Podiatric Medicine, a Doctor of Podiatric Medicine (DPM) is a medical specialist who diagnoses and treats conditions affecting the foot, ankle, and structures of the leg.[5] The US podiatric medical school curriculum includes lower extremity anatomy, general human anatomy, physiology, general medicine, physical assessment, biochemistry, neurobiology, pathophysiology, genetics and embryology, microbiology, histology, pharmacology, women's health, physical rehabilitation, sports medicine, research, ethics and jurisprudence, biomechanics, general principles of orthopedic surgery, and foot and ankle surgery.

    US trained podiatrists rotate through major areas of medicine during residency, including emergency medicine, orthopedic surgery, general surgery, anesthesia, radiology, pathology, infectious disease, endocrinology, sports medicine, physical therapy, biomechanics, geriatrics, internal medicine,[6] critical care, cardiology, vascular surgery, psychiatric and behavioral health, neurology, pediatrics, dermatology, pain management, wound care, and primary care.[7]
    """,
    
    """
    A podiatrist (/poʊˈdaɪətrɪst/ poh-dye-eh-trist), also known as a podiatric physician[1] or foot and ankle surgeon, is a medical professional devoted to the treatment of disorders of the foot, ankle, and lower extremity.[2] The term originated in North America, but has now become the accepted term in the English-speaking world for all practitioners of podiatric medicine.

    In the United States, Doctors of Podiatric Medicine (DPM) are doctors who practice on the lower extremities, primarily on feet and ankles.[3] The preparatory education of most podiatrists includes four years of undergraduate work, followed by four years in an accredited podiatric medical school, followed by a three or four-year hospital-based surgical residency. Podiatrists are licensed in all 50 states, but each state has their own licensing requirements. The scope of practice may vary from state to state and residency training.[4]

    Worldwide, in many countries the term podiatrist refers to allied health professionals who specialize in the treatment of the lower extremity, particularly the foot. Podiatrists in these countries are specialists in the diagnosis and treatment of foot pathology, but not through surgical means. In some circumstances these practitioners will further specialise and, following further training, perform reconstructive foot and ankle surgery.

    In contrast, American podiatrists who hold a Doctor of Podiatric Medicine (D.P.M.) complete surgical residencies, and thus all practitioners are trained in surgical treatments of the foot and ankle.[2] Though the title chiropodist was previously used in the United States to designate what is now known as a podiatrist, it is now considered to be an antiquated and etymologically incorrect term. The median annual Podiatry salary is approximately $195,000 as of August, 2018, with a wide range depending on years in practice. New Podiatrists right out of residency usually earn significantly less. First year salaries of $120,000-$180,0000 with performance and productivity incentives are common. Private practice revenue for solo Podiatrists also varies widely with the majority of solo practices grossing between $200,000-$600,000 before overhead. [5]
    """,
    
    """
    Biochemistry is the application of chemistry to the study of biological processes at the cellular and molecular level. It emerged as a distinct discipline around the beginning of the 20th century when scientists combined chemistry, physiology, and biology to investigate the chemistry of living systems.

    The study of life in its chemical processes
    Biochemistry is both life science and a chemical science - it explores the chemistry of living organisms and the molecular basis for the changes occurring in living cells. It uses the methods of chemistry,

    "Biochemistry has become the foundation for understanding all biological processes. It has provided explanations for the causes of many diseases in humans, animals and plants."

    physics, molecular biology, and immunology to study the structure and behaviour of the complex molecules found in biological material and the ways these molecules interact to form cells, tissues, and whole organisms.

    Biochemists are interested, for example, in mechanisms of brain function, cellular multiplication and differentiation, communication within and between cells and organs, and the chemical bases of inheritance and disease. The biochemist seeks to determine how specific molecules such as proteins, nucleic acids, lipids, vitamins, and hormones function in such processes. Particular emphasis is placed on the regulation of chemical reactions in living cells.
    """,
    
    """
    Biochemistry, study of the chemical substances and processes that occur in plants, animals, and microorganisms and of the changes they undergo during development and life. It deals with the chemistry of life, and as such it draws on the techniques of analytical, organic, and physical chemistry, as well as those of physiologists concerned with the molecular basis of vital processes. All chemical changes within the organism—either the degradation of substances, generally to gain necessary energy, or the buildup of complex molecules necessary for life processes—are collectively termed metabolism. These chemical changes depend on the action of organic catalysts known as enzymes, and enzymes, in turn, depend for their existence on the genetic apparatus of the cell. It is not surprising, therefore, that biochemistry enters into the investigation of chemical changes in disease, drug action, and other aspects of medicine, as well as in nutrition, genetics, and agriculture.

    The term biochemistry is synonymous with two somewhat older terms: physiological chemistry and biological chemistry. Those aspects of biochemistry that deal with the chemistry and function of very large molecules (e.g., proteins and nucleic acids) are often grouped under the term molecular biology. Biochemistry is a young science, having been known under that term only since about 1900. Its origins, however, can be traced much further back; its early history is part of the early history of both physiology and chemistry.

    Historical Background
    The particularly significant past events in biochemistry have been concerned with placing biological phenomena on firm chemical foundations.


    Before chemistry could contribute adequately to medicine and agriculture, however, it had to free itself from immediate practical demands in order to become a pure science. This happened in the period from about 1650 to 1780, starting with the work of Robert Boyle and culminating in that of Antoine-Laurent Lavoisier, the father of modern chemistry. Boyle questioned the basis of the chemical theory of his day and taught that the proper object of chemistry was to determine the composition of substances. His contemporary John Mayow observed the fundamental analogy between the respiration of an animal and the burning, or oxidation, of organic matter in air. Then, when Lavoisier carried out his fundamental studies on chemical oxidation, grasping the true nature of the process, he also showed, quantitatively, the similarity between chemical oxidation and the respiratory process. Photosynthesis was another biological phenomenon that occupied the attention of the chemists of the late 18th century. The demonstration, through the combined work of Joseph Priestley, Jan Ingenhousz, and Jean Senebier, that photosynthesis is essentially the reverse of respiration was a milestone in the development of biochemical thought.

    In spite of these early fundamental discoveries, rapid progress in biochemistry had to wait upon the development of structural organic chemistry, one of the great achievements of 19th-century science. A living organism contains many thousands of different chemical compounds. The elucidation of the chemical transformations undergone by these compounds within the living cell is a central problem of biochemistry. Clearly, the determination of the molecular structure of the organic substances present in living cells had to precede the study of the cellular mechanisms, whereby these substances are synthesized and degraded.

    There are few sharp boundaries in science, and the boundaries between organic and physical chemistry, on the one hand, and biochemistry, on the other, have always shown much overlap. Biochemistry has borrowed the methods and theories of organic and physical chemistry and applied them to physiological problems. Progress in this path was at first impeded by a stubborn misconception in scientific thinking—the error of supposing that the transformations undergone by matter in the living organism were not subject to the chemical and physical laws that applied to inanimate substances and that consequently these “vital” phenomena could not be described in ordinary chemical or physical terms. Such an attitude was taken by the vitalists, who maintained that natural products formed by living organisms could never be synthesized by ordinary chemical means. The first laboratory synthesis of an organic compound, urea, by Friedrich Wöhler in 1828, was a blow to the vitalists but not a decisive one. They retreated to new lines of defense, arguing that urea was only an excretory substance—a product of breakdown and not of synthesis. The success of the organic chemists in synthesizing many natural products forced further retreats of the vitalists. It is axiomatic in modern biochemistry that the chemical laws that apply to inanimate materials are equally valid within the living cell.

    At the same time that progress was being impeded by a misplaced kind of reverence for living phenomena, the practical needs of man operated to spur the progress of the new science. As organic and physical chemistry erected an imposing body of theory in the 19th century, the needs of the physician, the pharmacist, and the agriculturalist provided an ever-present stimulus for the application of the new discoveries of chemistry to various urgent practical problems.

    Two outstanding figures of the 19th century, Justus von Liebig and Louis Pasteur, were particularly responsible for dramatizing the successful application of chemistry to the study of biology. Liebig studied chemistry in Paris and carried back to Germany the inspiration gained by contact with the former students and colleagues of Lavoisier. He established at Giessen a great teaching and research laboratory, one of the first of its kind, which drew students from all over Europe.

    Besides putting the study of organic chemistry on a firm basis, Liebig engaged in extensive literary activity, attracting the attention of all scientists to organic chemistry and popularizing it for the layman as well. His classic works, published in the 1840s, had a profound influence on contemporary thought. Liebig described the great chemical cycles in nature. He pointed out that animals would disappear from the face of the Earth if it were not for the photosynthesizing plants, since animals require for their nutrition the complex organic compounds that can be synthesized only by plants. The animal excretions and the animal body after death are also converted by a process of decay to simple products that can be re-utilized only by plants.

    In contrast with animals, green plants require for their growth only carbon dioxide, water, mineral salts, and sunlight. The minerals must be obtained from the soil, and the fertility of the soil depends on its ability to furnish the plants with these essential nutrients. But the soil is depleted of these materials by the removal of successive crops; hence the need for fertilizers. Liebig pointed out that chemical analysis of plants could serve as a guide to the substances that should be present in fertilizers. Agricultural chemistry as an applied science was thus born.
    """,
    
    """
    It's one of the biggest decisions you make before your baby is born. Which pediatrician is the right one for your child? Before you start your search, take a few minutes to learn exactly what this kind of doctor does. It will help you make a better choice and know what to expect when your little one arrives.

    Pediatricians are doctors who manage the health of your child, including physical, behavior, and mental health issues. They're trained to diagnose and treat childhood illnesses, from minor health problems to serious diseases.

    Pediatricians have an education that gives them special skills to take care of your child's health. They graduated from medical school and completed a 3-year residency program in pediatrics.

    You'll want to find one who's also "board-certified." That means they've passed rigorous exams given by the American Board of Pediatrics. To stay certified, pediatricians have to meet regular education requirements.

    What Does Your Pediatrician Do?
    They'll see your child many times from birth to age 2 and once a year from ages 2 to 5 for "well-child visits." After age 5, your pediatrician will likely continue to see your child every year for annual checkups. They're also the first person to call whenever your child is sick.

    To take care of your child, your pediatrician will:

    Do physical exams
    Give your child vaccinations
    Make sure she meets milestones in growth, behavior, and skills
    Diagnose and treat your child's illnesses, infections, injuries, and other health problems
    Give you information about your child's health, safety, nutrition, and fitness needs
    Answer your questions about your little one's growth and development
    Refer you to specialists if they think your child needs expert care
    How Does Your Pediatrician Work With Your Delivery Team?
    Most hospitals ask if you have a pediatrician when you go in to deliver. Your baby's first examination may be with a hospital pediatrician or your chosen pediatrician. It depends on the hospital's policy and whether your newborn's doctor makes rounds there. If a hospital pediatrician checks your baby, they'll send your pediatrician notes about the exam.

    After you leave the hospital, your pediatrician will see your baby 48 to 72 hours later, and regularly after that for checkups.

    Why Do You Need a Pediatrician?
    One thing to keep in mind: Family medicine doctors are also an option for your child. They look after the health of your whole family -- kids and grown-ups alike. It's a personal choice whether you use one or a pediatrician.

    Some reasons to go with a pediatrician are:

    They have special training in children's health.
    They only see children in their practice, so they have a lot of experience in recognizing and treating childhood illnesses.
    If your child was born early or has a health condition that needs close monitoring, a pediatrician may offer more specialized care.
    """,
]

target_train = [
    0,
    1,
    0,
    1,
    1,
    2,
    2,
    0,
]

# testing
corpus_test = [
    """
    Forensic Podiatry is a subdiscipline of forensic science in which specialized podiatric knowledge including foot and lower limb anatomy, musculoskeletal function, deformities and diseases of the foot, ankle, lower extremities, and at times, the entire human body is used in the examination of foot-related evidence in the context of a criminal investigation. Forensic Podiatry has been defined as:

    The application of sound and researched podiatry knowledge and experience in forensic investigations, to show the association of an individual with a scene of crime, or to answer any other legal question concerned with the foot or footwear that requires knowledge of the functioning foot (Vernon & McCourt, 1999)

    Those who specialize in this field need to have gained knowledge and experience in podiatry and also in forensic science and practice (Vernon et al., 2009).

    Forensic Podiatry is usually used to assist in the process of human identification, but can also be employed to help address issues relating to questions that have arisen within the context of forensic enquiry. Such questions could include whether or not a shoe could have had multiple wearers, what the effects of a shoe not fitting correctly could have been, whether or not someone could have placed their foot into a shoe that was too small for the postulated wearer’s foot and other matters involving the podiatric interpretation of relevant evidential materials.
    """,
    
    """
    Background: Early childhood exposure carries an enhanced radiation risk and estimated that the probability of induction of cancer especially leukemia is about two to three times as high as in adults. Hence, dose measurement is mandatory for optimization in radiation protection to comply with international reference levels.

    Objectives: To estimate pediatric patient’s radiation dose arising from common diagnostic x-ray examinations by measuring Entrance Surface Dose, thereby, to compare the results from established reference values and other published studies.

    Material and Methods: A cross-sectional study was conducted on pediatric patients under 15 years of age in Black Lion and Yekatite 12 Hospitals on May and August, 2009 respectively. Exposure factors used for commonly performed x-ray examinations like; chest, skull, abdomen, pelvis and spine were obtained from each Hospital. For each examination. four age groups 0–1, 1–5, 5–10 and 10–15 years were studied. Entrance Surface Dose in air was measured using dositime dx X-ray Digital Dosimeter and Exposure Time Meter. Th e obtained data were analyzed using statistical soft ware.

    Result: In Black lion hospital, the lowest and the highest calculated mean Entrance Surface Doses in μGY were 104 and 2482 for chest Anteroposterior (0-1) years and lumbo-sacral lateral (10 -15) years, respectively. In Yekatit 12 hospital, the lowest and the highest calculated mean Entrance Surface Doses in μGY were 200 and 3570 for chest antrioposterior (0-1) years and lumbo-sacral lateral ( 10 -15)years, respectively. Wide variations of doses for the same type of examination and projection have been detected in each hospital.

    Conclusion: Th e wider dose variation suggests that there is a pressing need to seek dose optimization to children in order to reduce the detriment caused by the unnecessary high doses imparted to them.
    """,
]

target_test = [
    1,
    0,
]

# target_labels[taget] is the label of the predict value
target_labels = [
    "Pediatrics",
    "Podiatry",
    "Biochemistry",
    
]

"""# Train and predict"""

# allsentences = ["Joe waited for the train", "The train was late", "Mary and Samantha took the bus", "I looked for Mary and Samantha at the bus station","Mary and Samantha arrived at the bus station early but waited until noon for the bus"]
# generate_bow(allsentences)

print("Com a biblioteca:")


vectorizer = CountVectorizer(stop_words=stop_words)
X = vectorizer.fit_transform(corpus_train)



X_train,X_test,y_train,y_test = train_test_split(X, target_train, test_size=0.3, random_state=10)
#print(X_train.toarray())

mySVC = SVC()

# train
mySVC.fit(X_train, y_train)

preds = mySVC.predict(X_test)
# print(preds)


acc = accuracy_score(y_test, preds)
print(acc)

220
print("############################")

my_vocabulary = vectorizer.vocabulary_
print(my_vocabulary)

newVectorizer = CountVectorizer(vocabulary=my_vocabulary, stop_words=stop_words)
X_test = newVectorizer.fit_transform(corpus_test)


preds = mySVC.predict(X_test)
print(preds)
acc = accuracy_score(target_test, preds)
print(acc)

# Não dá pra usar isso
# acc = accuracy_score(y_test, preds)
